# TCL File Generated by Component Editor 13.1
# Thu Jul 10 22:25:21 CEST 2014
# DO NOT MODIFY


# 
# leon3_SDRAM_uart_DE2115 "leon3_SDRAM_uart_DE2115" v1.0
# Francesco Robino 2014.07.10.22:25:20
# leon3 connected to SDRAM, using uart as debug port, for DE2115 board
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module leon3_SDRAM_uart_DE2115
# 
set_module_property DESCRIPTION "leon3 connected to SDRAM, using uart as debug port, for DE2115 board"
set_module_property NAME leon3_SDRAM_uart_DE2115
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP leon_cores
set_module_property AUTHOR "Francesco Robino"
set_module_property DISPLAY_NAME leon3_SDRAM_uart_DE2115
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL leon3mp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file config2.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/designs/leon3-terasic-de2-115/config2.vhd
add_fileset_file leon3mp2.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/designs/leon3-terasic-de2-115/leon3mp2.vhd TOP_LEVEL_FILE
add_fileset_file top_level2.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/designs/leon3-terasic-de2-115/top_level2.vhd
add_fileset_file mctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/esa/memoryctrl/mctrl.vhd
add_fileset_file memoryctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/esa/memoryctrl/memoryctrl.vhd
add_fileset_file spi.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spi.vhd
add_fileset_file spi2ahb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spi2ahb.vhd
add_fileset_file spi2ahb_apb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spi2ahb_apb.vhd
add_fileset_file spi2ahbx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spi2ahbx.vhd
add_fileset_file spictrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spictrl.vhd
add_fileset_file spictrlx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spictrlx.vhd
add_fileset_file spimctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/spi/spimctrl.vhd
add_fileset_file i2c.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2c.vhd
add_fileset_file i2c2ahb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2c2ahb.vhd
add_fileset_file i2c2ahb_apb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2c2ahb_apb.vhd
add_fileset_file i2c2ahb_apb_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2c2ahb_apb_gen.vhd
add_fileset_file i2c2ahb_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2c2ahb_gen.vhd
add_fileset_file i2c2ahbx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2c2ahbx.vhd
add_fileset_file i2cmst.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2cmst.vhd
add_fileset_file i2cmst_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2cmst_gen.vhd
add_fileset_file i2cslv.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/i2c/i2cslv.vhd
add_fileset_file ethernet_mac.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/ethernet_mac.vhd
add_fileset_file greth.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/greth.vhd
add_fileset_file greth_gbit.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/greth_gbit.vhd
add_fileset_file greth_gbit_mb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/greth_gbit_mb.vhd
add_fileset_file greth_mb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/greth_mb.vhd
add_fileset_file grethm.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/grethm.vhd
add_fileset_file rgmii.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/greth/rgmii.vhd
add_fileset_file ahbjtag.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/ahbjtag.vhd
add_fileset_file ahbjtag_bsd.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/ahbjtag_bsd.vhd
add_fileset_file bscanregs.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/bscanregs.vhd
add_fileset_file bscanregsbd.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/bscanregsbd.vhd
add_fileset_file jtag.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/jtag.vhd
add_fileset_file jtagcom.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/jtagcom.vhd
add_fileset_file jtagcom2.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/jtagcom2.vhd
add_fileset_file jtagtst.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/jtagtst.vhd
add_fileset_file libjtagcom.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/jtag/libjtagcom.vhd
add_fileset_file ahbuart.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/uart/ahbuart.vhd
add_fileset_file apbuart.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/uart/apbuart.vhd
add_fileset_file dcom.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/uart/dcom.vhd
add_fileset_file dcom_uart.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/uart/dcom_uart.vhd
add_fileset_file libdcom.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/uart/libdcom.vhd
add_fileset_file uart.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/uart/uart.vhd
add_fileset_file net.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/net/net.vhd
add_fileset_file ahb_mst_iface.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahb_mst_iface.vhd
add_fileset_file ahbdma.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbdma.vhd
add_fileset_file ahbdpram.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbdpram.vhd
add_fileset_file ahbram.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbram.vhd
add_fileset_file ahbstat.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbstat.vhd
add_fileset_file ahbtrace.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbtrace.vhd
add_fileset_file ahbtrace_mb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbtrace_mb.vhd
add_fileset_file ahbtrace_mmb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/ahbtrace_mmb.vhd
add_fileset_file apbps2.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/apbps2.vhd
add_fileset_file apbvga.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/apbvga.vhd
add_fileset_file charrom.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/charrom.vhd
add_fileset_file charrom_package.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/charrom_package.vhd
add_fileset_file gptimer.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/gptimer.vhd
add_fileset_file gracectrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/gracectrl.vhd
add_fileset_file grgpio.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/grgpio.vhd
add_fileset_file grgprbank.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/grgprbank.vhd
add_fileset_file grgpreg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/grgpreg.vhd
add_fileset_file grsysmon.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/grsysmon.vhd
add_fileset_file logan.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/logan.vhd
add_fileset_file misc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/misc.vhd
add_fileset_file rstgen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/rstgen.vhd
add_fileset_file svgactrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/misc/svgactrl.vhd
add_fileset_file can.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/can/can.vhd
add_fileset_file can_mc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/can/can_mc.vhd
add_fileset_file can_mod.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/can/can_mod.vhd
add_fileset_file can_oc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/can/can_oc.vhd
add_fileset_file can_rd.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/can/can_rd.vhd
add_fileset_file canmux.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/can/canmux.vhd
add_fileset_file l2cache.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/l2cache/v2-pkg/l2cache.vhd
add_fileset_file irqmp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/irqmp/irqmp.vhd
add_fileset_file cachemem.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/cachemem.vhd
add_fileset_file dsu3.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/dsu3.vhd
add_fileset_file dsu3_mb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/dsu3_mb.vhd
add_fileset_file dsu3x.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/dsu3x.vhd
add_fileset_file grfpwx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/grfpwx.vhd
add_fileset_file grfpwxsh.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/grfpwxsh.vhd
add_fileset_file grlfpwx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/grlfpwx.vhd
add_fileset_file iu3.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/iu3.vhd
add_fileset_file leon3cg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/leon3cg.vhd
add_fileset_file leon3s.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/leon3s.vhd
add_fileset_file leon3sh.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/leon3sh.vhd
add_fileset_file leon3x.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/leon3x.vhd
add_fileset_file libcache.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/libcache.vhd
add_fileset_file libfpu.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/libfpu.vhd
add_fileset_file libiu.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/libiu.vhd
add_fileset_file libleon3.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/libleon3.vhd
add_fileset_file mmu_acache.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/mmu_acache.vhd
add_fileset_file mmu_cache.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/mmu_cache.vhd
add_fileset_file mmu_dcache.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/mmu_dcache.vhd
add_fileset_file mmu_icache.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/mmu_icache.vhd
add_fileset_file proc3.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/proc3.vhd
add_fileset_file regfile_3p_l3.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/regfile_3p_l3.vhd
add_fileset_file tbufmem.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3v3/tbufmem.vhd
add_fileset_file libmmu.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/libmmu.vhd
add_fileset_file mmu.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmu.vhd
add_fileset_file mmuconfig.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmuconfig.vhd
add_fileset_file mmuiface.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmuiface.vhd
add_fileset_file mmulru.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmulru.vhd
add_fileset_file mmulrue.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmulrue.vhd
add_fileset_file mmutlb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmutlb.vhd
add_fileset_file mmutlbcam.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmutlbcam.vhd
add_fileset_file mmutw.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/srmmu/mmutw.vhd
add_fileset_file memctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/memctrl/memctrl.vhd
add_fileset_file sdctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/memctrl/sdctrl.vhd
add_fileset_file sdctrl64.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/memctrl/sdctrl64.vhd
add_fileset_file sdmctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/memctrl/sdmctrl.vhd
add_fileset_file srctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/memctrl/srctrl.vhd
add_fileset_file arith.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/arith/arith.vhd
add_fileset_file div32.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/arith/div32.vhd
add_fileset_file mul32.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/arith/mul32.vhd
add_fileset_file i2c_master_bit_ctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/opencores/i2c/i2c_master_bit_ctrl.vhd
add_fileset_file i2c_master_byte_ctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/opencores/i2c/i2c_master_byte_ctrl.vhd
add_fileset_file i2coc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/opencores/i2c/i2coc.vhd
add_fileset_file can_top.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/opencores/can/can_top.vhd
add_fileset_file cancomp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/opencores/can/cancomp.vhd
add_fileset_file greth_gbit_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/wrapper/greth_gbit_gen.vhd
add_fileset_file greth_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/wrapper/greth_gen.vhd
add_fileset_file eth_ahb_mst.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/eth_ahb_mst.vhd
add_fileset_file eth_edcl_ahb_mst.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/eth_edcl_ahb_mst.vhd
add_fileset_file eth_rstgen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/eth_rstgen.vhd
add_fileset_file greth_pkg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/greth_pkg.vhd
add_fileset_file greth_rx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/greth_rx.vhd
add_fileset_file greth_tx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/greth_tx.vhd
add_fileset_file grethc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/core/grethc.vhd
add_fileset_file ethcomp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/eth/comp/ethcomp.vhd
add_fileset_file grspw2_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/spw/wrapper/grspw2_gen.vhd
add_fileset_file grspw_codec_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/spw/wrapper/grspw_codec_gen.vhd
add_fileset_file grspw_gen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/spw/wrapper/grspw_gen.vhd
add_fileset_file spwcomp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/spw/comp/spwcomp.vhd
add_fileset_file allclkgen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/allclkgen.vhd
add_fileset_file allddr.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/allddr.vhd
add_fileset_file allmem.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/allmem.vhd
add_fileset_file allmul.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/allmul.vhd
add_fileset_file allpads.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/allpads.vhd
add_fileset_file alltap.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/alltap.vhd
add_fileset_file clkand.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/clkand.vhd
add_fileset_file clkgen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/clkgen.vhd
add_fileset_file clkinv.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/clkinv.vhd
add_fileset_file clkmux.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/clkmux.vhd
add_fileset_file clkpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/clkpad.vhd
add_fileset_file clkpad_ds.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/clkpad_ds.vhd
add_fileset_file cpu_disas_net.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/cpu_disas_net.vhd
add_fileset_file ddr_ireg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/ddr_ireg.vhd
add_fileset_file ddr_oreg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/ddr_oreg.vhd
add_fileset_file ddrphy.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/ddrphy.vhd
add_fileset_file grfpw_net.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/grfpw_net.vhd
add_fileset_file grgates.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/grgates.vhd
add_fileset_file grlfpw_net.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/grlfpw_net.vhd
add_fileset_file inpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/inpad.vhd
add_fileset_file inpad_ddr.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/inpad_ddr.vhd
add_fileset_file inpad_ds.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/inpad_ds.vhd
add_fileset_file iodpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/iodpad.vhd
add_fileset_file iopad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/iopad.vhd
add_fileset_file iopad_ddr.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/iopad_ddr.vhd
add_fileset_file iopad_ds.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/iopad_ds.vhd
add_fileset_file leon4_net.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/leon4_net.vhd
add_fileset_file lvds_combo.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/lvds_combo.vhd
add_fileset_file mul_61x61.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/mul_61x61.vhd
add_fileset_file nandtree.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/nandtree.vhd
add_fileset_file odpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/odpad.vhd
add_fileset_file outpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/outpad.vhd
add_fileset_file outpad_ddr.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/outpad_ddr.vhd
add_fileset_file outpad_ds.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/outpad_ds.vhd
add_fileset_file regfile_3p.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/regfile_3p.vhd
add_fileset_file ringosc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/ringosc.vhd
add_fileset_file scanreg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/scanreg.vhd
add_fileset_file sdram_phy.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/sdram_phy.vhd
add_fileset_file skew_outpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/skew_outpad.vhd
add_fileset_file spictrl_net.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/spictrl_net.vhd
add_fileset_file syncfifo_2p.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncfifo_2p.vhd
add_fileset_file syncram.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram.vhd
add_fileset_file syncram128.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram128.vhd
add_fileset_file syncram128bw.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram128bw.vhd
add_fileset_file syncram156bw.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram156bw.vhd
add_fileset_file syncram256bw.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram256bw.vhd
add_fileset_file syncram64.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram64.vhd
add_fileset_file syncram_2p.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram_2p.vhd
add_fileset_file syncram_2pbw.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram_2pbw.vhd
add_fileset_file syncram_dp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncram_dp.vhd
add_fileset_file syncrambw.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncrambw.vhd
add_fileset_file syncreg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/syncreg.vhd
add_fileset_file system_monitor.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/system_monitor.vhd
add_fileset_file tap.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/tap.vhd
add_fileset_file techbuf.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/techbuf.vhd
add_fileset_file techmult.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/techmult.vhd
add_fileset_file toutpad.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/toutpad.vhd
add_fileset_file toutpad_ds.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/maps/toutpad_ds.vhd
add_fileset_file cycloneiii_clkgen.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/cycloneiii_clkgen.vhd
add_fileset_file ddr_phy_cycloneiii.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/ddr_phy_cycloneiii.vhd
add_fileset_file aclkout.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/aclkout.vhd
add_fileset_file actrlout.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/actrlout.vhd
add_fileset_file admout.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/admout.vhd
add_fileset_file adqin.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/adqin.vhd
add_fileset_file adqout.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/adqout.vhd
add_fileset_file adqsin.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/adqsin.vhd
add_fileset_file adqsout.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/adqsout.vhd
add_fileset_file apll.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/cycloneiii/alt/apll.vhd
add_fileset_file clkgen_altera_mf.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/altera_mf/clkgen_altera_mf.vhd
add_fileset_file memory_altera_mf.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/altera_mf/memory_altera_mf.vhd
add_fileset_file tap_altera_mf.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/altera_mf/tap_altera_mf.vhd
add_fileset_file ddr_inferred.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/inferred/ddr_inferred.vhd
add_fileset_file ddr_phy_inferred.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/inferred/ddr_phy_inferred.vhd
add_fileset_file ddrphy_datapath.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/inferred/ddrphy_datapath.vhd
add_fileset_file lpddr2_phy_inferred.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/inferred/lpddr2_phy_inferred.vhd
add_fileset_file memory_inferred.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/inferred/memory_inferred.vhd
add_fileset_file mul_inferred.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/inferred/mul_inferred.vhd
add_fileset_file gencomp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/gencomp/gencomp.vhd
add_fileset_file netcomp.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/techmap/gencomp/netcomp.vhd
add_fileset_file ahbctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/ahbctrl.vhd
add_fileset_file ahbmst.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/ahbmst.vhd
add_fileset_file amba.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/amba.vhd
add_fileset_file apbctrl.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/apbctrl.vhd
add_fileset_file defmst.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/defmst.vhd
add_fileset_file devices.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/devices.vhd
add_fileset_file dma2ahb.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/dma2ahb.vhd
add_fileset_file dma2ahb_pkg.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/amba/dma2ahb_pkg.vhd
add_fileset_file leaves.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/modgen/leaves.vhd
add_fileset_file multlib.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/modgen/multlib.vhd
add_fileset_file cpu_disas.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/sparc/cpu_disas.vhd
add_fileset_file sparc.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/sparc/sparc.vhd
add_fileset_file sparc_disas.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/sparc/sparc_disas.vhd
add_fileset_file config_types.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/stdlib/config_types.vhd
add_fileset_file stdio.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/stdlib/stdio.vhd
add_fileset_file stdlib.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/stdlib/stdlib.vhd
add_fileset_file testlib.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/stdlib/testlib.vhd
add_fileset_file version.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/stdlib/version.vhd
add_fileset_file cpu_disasx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3/cpu_disasx.vhd
add_fileset_file grfpushwx.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3/grfpushwx.vhd
add_fileset_file leon3.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/gaisler/leon3/leon3.vhd
add_fileset_file config.vhd VHDL PATH ../grlib-gpl-1.3.7-b4144/lib/grlib/stdlib/config.vhd


# 
# parameters
# 
add_parameter fabtech INTEGER 27
set_parameter_property fabtech DEFAULT_VALUE 27
set_parameter_property fabtech DISPLAY_NAME fabtech
set_parameter_property fabtech TYPE INTEGER
set_parameter_property fabtech UNITS None
set_parameter_property fabtech HDL_PARAMETER true
add_parameter memtech INTEGER 27
set_parameter_property memtech DEFAULT_VALUE 27
set_parameter_property memtech DISPLAY_NAME memtech
set_parameter_property memtech TYPE INTEGER
set_parameter_property memtech UNITS None
set_parameter_property memtech HDL_PARAMETER true
add_parameter padtech INTEGER 27
set_parameter_property padtech DEFAULT_VALUE 27
set_parameter_property padtech DISPLAY_NAME padtech
set_parameter_property padtech TYPE INTEGER
set_parameter_property padtech UNITS None
set_parameter_property padtech HDL_PARAMETER true
add_parameter clktech INTEGER 27
set_parameter_property clktech DEFAULT_VALUE 27
set_parameter_property clktech DISPLAY_NAME clktech
set_parameter_property clktech TYPE INTEGER
set_parameter_property clktech UNITS None
set_parameter_property clktech HDL_PARAMETER true
add_parameter disas INTEGER 0
set_parameter_property disas DEFAULT_VALUE 0
set_parameter_property disas DISPLAY_NAME disas
set_parameter_property disas TYPE INTEGER
set_parameter_property disas UNITS None
set_parameter_property disas HDL_PARAMETER true
add_parameter dbguart INTEGER 0
set_parameter_property dbguart DEFAULT_VALUE 0
set_parameter_property dbguart DISPLAY_NAME dbguart
set_parameter_property dbguart TYPE INTEGER
set_parameter_property dbguart UNITS None
set_parameter_property dbguart HDL_PARAMETER true
add_parameter pclow INTEGER 2
set_parameter_property pclow DEFAULT_VALUE 2
set_parameter_property pclow DISPLAY_NAME pclow
set_parameter_property pclow TYPE INTEGER
set_parameter_property pclow UNITS None
set_parameter_property pclow HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_50 clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset resetn reset_n Input 1


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_data_rd readdata Input 32
add_interface_port avalon_master_0 avm_data_wr writedata Output 32
add_interface_port avalon_master_0 avm_address address Output 32
add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_byteenable byteenable Output 4
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end errorn export Output 1
add_interface_port conduit_end dram_addr export Output 13
add_interface_port conduit_end dram_ba export Output 2
add_interface_port conduit_end dram_dq export Bidir 32
add_interface_port conduit_end dram_clk export Output 1
add_interface_port conduit_end dram_cke export Output 1
add_interface_port conduit_end dram_cs_n export Output 1
add_interface_port conduit_end dram_we_n export Output 1
add_interface_port conduit_end dram_ras_n export Output 1
add_interface_port conduit_end dram_cas_n export Output 1
add_interface_port conduit_end dram_dqm export Output 4
add_interface_port conduit_end uart_txd export Output 1
add_interface_port conduit_end uart_rxd export Input 1
add_interface_port conduit_end dsubre export Input 1
add_interface_port conduit_end dsuact export Output 1

